heat_template_version: '2018-08-31'
description: >
  Provisions a virtual machine on OpenStack to run a Minecraft Bedrock server.
  Includes network setup, floating IP assignment, and customizable
  server.properties values.
parameters:
  flavor:
    type: string
    description: Flavor of the instance
    default: gp.5.4.4
  image:
    type: string
    description: Image to use for the instance
    default: Ubuntu 20.04
  key_name:
    type: string
    description: SSH key name to access the instance
    default: default-key
  public_net_id:
    type: string
    description: ID of the public network
    default: PUBLICNET
  level_name:
    type: string
    default: Bedrock_World
  level_seed:
    type: string
    default: ''
  level_type:
    type: string
    default: DEFAULT
  difficulty:
    type: string
    default: easy
  gamemode:
    type: string
    default: survival
  max_players:
    type: number
    default: 10
  allow_cheats:
    type: boolean
    default: false
resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: private_net
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id:
        get_resource: private_net
      cidr: 192.168.0.0/24
      gateway_ip: 192.168.0.1
      ip_version: 4
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4
  router:
    type: OS::Neutron::Router
    properties:
      name: router
      external_gateway_info:
        network:
          get_param: public_net_id
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id:
        get_resource: router
      subnet_id:
        get_resource: private_subnet
  instance_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: bedrock_security_group
      rules:
        - direction: ingress
          ethertype: IPv4
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - direction: ingress
          ethertype: IPv4
          protocol: udp
          port_range_min: 19132
          port_range_max: 19133
        - direction: egress
          ethertype: IPv4
  instance_port:
    type: OS::Neutron::Port
    properties:
      network_id:
        get_resource: private_net
      security_groups:
        - get_resource: instance_security_group
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id:
        get_param: public_net_id
      port_id:
        get_resource: instance_port
  instance:
    type: OS::Nova::Server
    properties:
      flavor:
        get_param: flavor
      image:
        get_param: image
      key_name:
        get_param: key_name
      networks:
        - port:
            get_resource: instance_port
      user_data:
        str_replace:
          template: >
            #!/bin/bash

            apt-get update -y

            apt-get install -y curl unzip libssl1.1 screen


            useradd -m -r -d /opt/bedrock bedrock


            mkdir -p /opt/bedrock/server

            chown bedrock:bedrock /opt/bedrock/server


            sudo -u bedrock bash <<EOF

            cd /opt/bedrock/server

            curl -sSL -o bedrock.zip
            https://04570bd530fbf4c6ec9a-a5cff7ad7a8d83cb3fa8718d4931d0d2.ssl.cf1.rackcdn.com/bedrock-server-1.21.84.1.zip

            unzip -o bedrock.zip

            rm bedrock.zip

            chmod +x bedrock_server


            cat > server.properties <<EOP

            level-name=${level_name}

            level-seed=${level_seed}

            level-type=${level_type}

            difficulty=${difficulty}

            gamemode=${gamemode}

            max-players=${max_players}

            allow-cheats=${allow_cheats}

            EOP

            EOF


            cat <<EOL > /etc/systemd/system/bedrock.service

            [Unit]

            Description=Minecraft Bedrock Server

            After=network.target


            [Service]

            User=bedrock

            WorkingDirectory=/opt/bedrock/server

            ExecStart=/opt/bedrock/server/bedrock_server

            Restart=on-failure


            [Install]

            WantedBy=multi-user.target

            EOL


            systemctl daemon-reload

            systemctl enable bedrock

            systemctl start bedrock
          params:
            ${level_name}:
              get_param: level_name
            ${level_seed}:
              get_param: level_seed
            ${level_type}:
              get_param: level_type
            ${difficulty}:
              get_param: difficulty
            ${gamemode}:
              get_param: gamemode
            ${max_players}:
              get_param: max_players
            ${allow_cheats}:
              get_param: allow_cheats
outputs:
  instance_ip:
    description: Floating IP of the Minecraft Bedrock server instance
    value:
      get_attr:
        - floating_ip
        - floating_ip_address
